stages:
  - build
  - package

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"

build:
  stage: build
  image: gradle:8-jdk17-alpine
  script:
    - echo "Building user-service version ${VERSION}"
    - chmod +x gradlew
    - ./gradlew clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar

package:
  stage: package
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Pushed version $VERSION and latest"
  dependencies:
    - build
  only:
    - master
    - main
