variables:
  MAJOR: "1"
  MINOR: "0"
  VERSION: "v${MAJOR}.${MINOR}.${CI_PIPELINE_IID}"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$VERSION"
  DOCKER_DRIVER: overlay2

stages:
  - build
  - docker

build:
  stage: build
  image: eclipse-temurin:17-jdk-alpine
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew build -x test --no-daemon
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour
  only:
    - branches
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/

docker-build:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME -t $CI_REGISTRY_IMAGE:latest .
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Built and pushed $VERSION"
  only:
    - master
