variables:
  MAJOR: "1"
  MINOR: "0"
  VERSION: "v${MAJOR}.${MINOR}.${CI_PIPELINE_IID}"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$VERSION"

stages:
  - build
  - docker

build:
  stage: build
  image: eclipse-temurin:17-jdk
  script:
    - ./gradlew build -x test
  only:
    - branches

docker-build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - echo "Built version $VERSION"
  only:
    - master
