stages:
  - version
  - build
  - package
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

generate_version:
  stage: version
  image: alpine/git:latest
  script:
    - apk add --no-cache jq curl
    - LATEST_TAG=$(git tag --sort=-version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
    - |
      if [ -z "$LATEST_TAG" ]; then
        NEW_VERSION="1.0.1"
      else
        CURRENT_VERSION=${LATEST_TAG#v}
        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
        if [ $PATCH -lt 99 ]; then
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
        else
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="${MAJOR}.${NEW_MINOR}.0"
        fi
      fi
    - echo "VERSION=${NEW_VERSION}" > version.env
    - echo "VERSION_TAG=v${NEW_VERSION}" >> version.env
    - echo "New version will be v${NEW_VERSION}"
  artifacts:
    reports:
      dotenv: version.env

build:
  stage: build
  image: gradle:8-jdk17-alpine
  script:
    - echo "Building user-service version ${VERSION}"
    - chmod +x gradlew
    - ./gradlew clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  dependencies:
    - generate_version

package:
  stage: package
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Pushed version $VERSION and latest"
  dependencies:
    - build
    - generate_version
  only:
    - master
    - main

tag_release:
  stage: deploy
  image: alpine/git:latest
  before_script:
    - git config user.email "ci@gitlab.com"
    - git config user.name "GitLab CI"
    - git remote set-url origin https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
  script:
    - git tag -a ${VERSION_TAG} -m "Release user-service ${VERSION_TAG}"
    - git push origin ${VERSION_TAG}
    - echo "Tagged release ${VERSION_TAG}"
  dependencies:
    - generate_version
    - package
  only:
    - master
    - main
